name: my_exams
description: "Proyek exams PENS."
publish_to: 'none'
version: 2.1.3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.2
  get: ^4.3.8
  flutter_quill: ^11.1.0
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_delta_from_html: ^1.5.0
  flutter_html: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  audioplayers: ^6.4.0
  file_picker: ^10.1.2
  mime: ^2.0.0
  socket_io_client: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_easyloading: ^3.0.5
  flutter_phoenix: ^1.0.0
  restart_app: ^1.3.2
  js: ^0.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Poppins
    fonts:
      - asset: asset/font/Poppins-Regular.otf
      - asset: asset/font/Poppins-Medium.otf
      - asset: asset/font/Poppins-Bold.otf
      - asset: asset/font/Poppins-Italic.otf
      - asset: asset/font/Poppins-MediumItalic.otf
      - asset: asset/font/Poppins-BoldItalic.otf

flutter_icons:
  android: true
  ios: true
  image_path: "asset/Icons/image.png"

flutter_native_splash:
  color: "#ffffff"      
  image: asset/Icons/image.png
  android: true
  ios: true
  android_gravity: center 
  ios_content_mode: center
